name: vue frontend deployment
on:
  push:
    branches: [main]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'
          
      - name: Install dependencies
        run: npm install
        working-directory: ./frontEnd

      - name: Build Vue app
        run: npm run build
        working-directory: ./frontEnd
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontEnd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vue_frontend:${{ github.run_number }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: run ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 175.197.41.119
          username: test
          password: ${{ secrets.SSH_PASSWORD }}
          port: 224
          script: |
            if kubectl get svc dabom-front -n dabom -o wide | grep -q "green"; then
              CURRENT_VER="green"
              NEXT_VER="blue"
            else
              CURRENT_VER="blue"
              NEXT_VER="green"
            fi

            cat <<EOF | kubectl apply -f -
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: vue-deployment-${NEXT_VER}
              namespace: dabom
            spec:
              selector:
                matchLabels:
                  type: app
                  ver: ${NEXT_VER}
              replicas: 1
              strategy:
                type: RollingUpdate
              template:
                metadata:
                  labels:
                    type: app
                    ver: ${NEXT_VER}
                spec:
                  containers:
                    - name: container
                      image: ${{ secrets.DOCKERHUB_USERNAME }}/vue_frontend:${{ github.run_number }}
                      ports:
                        - containerPort: 80
                      livenessProbe:
                        httpGet:
                          path: /
                          port: 80
                        initialDelaySeconds: 10
                        periodSeconds: 10
                      readinessProbe:
                        httpGet:
                          path: /
                          port: 80
                        initialDelaySeconds: 10
                        periodSeconds: 5
                        successThreshold: 2
                  terminationGracePeriodSeconds: 0
            EOF


            kubectl patch service dabom-front -n dabom -p '{"spec":{"selector":{"ver":"'${NEXT_VER}'"}}}'
            kubectl scale deployment vue-deployment-${CURRENT_VER} -n dabom --replicas=0
            
            
